
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action newAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action buildAction;
	private global::Gtk.Action rebuildAction;
	private global::Gtk.Action cleanAction;
	private global::Gtk.Action stopAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Toolbar mainToolbar;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView assetsTree;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label assetTypeLabel;
	private global::Gtk.Label assetNameLabel;
	private global::Gtk.Notebook assetNotebook;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label2;
	private global::Gtk.ComboBox assetProcessorCombo;
	private global::Gdk.Framework.UI.GtkSharp.PropertyGrid assetPropertyGrid;
	private global::Gtk.Label propertiesTabPage;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView assetBuildLogTextView;
	private global::Gtk.Label buildLogTabPage;
	private global::Gtk.Notebook bottomNotebook;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.TextView buildLogTextView;
	private global::Gtk.HBox bottomNotebookTab1HBox;
	private global::Gtk.Image bottomNotebookTab1HBoxImage1;
	private global::Gtk.Label bottomNotebookTab1HBoxLabel1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.TreeView buildErrorsTreeView;
	private global::Gtk.HBox bottomNotebookTab2HBox;
	private global::Gtk.Image buildErrorsTabImage;
	private global::Gtk.Label buildErrorsTabLabel;
	private global::Gtk.Image buildWarningsTabImage;
	private global::Gtk.Label buildWarningsTabLabel;
	private global::Gtk.ScrolledWindow GtkScrolledWindow4;
	private global::Gtk.TreeView buildOutputsTreeView;
	private global::Gtk.HBox bottomNotebookTab3HBox;
	private global::Gtk.Image bottomNotebookTab3HBoxImage1;
	private global::Gtk.Label bottomNotebookTab3HBoxLabel1;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New"), global::Mono.Unix.Catalog.GetString ("Create a new GDK content bundle"), "gtk-new");
		this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.newAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open"), global::Mono.Unix.Catalog.GetString ("Open an existing GDK content bundle"), "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), global::Mono.Unix.Catalog.GetString ("Save any changes to this GDK content bundle"), "gtk-save");
		this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.saveAction, null);
		this.buildAction = new global::Gtk.Action ("buildAction", global::Mono.Unix.Catalog.GetString ("Build"), null, "gtk-execute");
		this.buildAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Build");
		w1.Add (this.buildAction, null);
		this.rebuildAction = new global::Gtk.Action ("rebuildAction", global::Mono.Unix.Catalog.GetString ("Rebuild"), null, "gtk-preferences");
		this.rebuildAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rebuild");
		w1.Add (this.rebuildAction, null);
		this.cleanAction = new global::Gtk.Action ("cleanAction", global::Mono.Unix.Catalog.GetString ("Clean"), null, "gtk-delete");
		this.cleanAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clean");
		w1.Add (this.cleanAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", global::Mono.Unix.Catalog.GetString ("Stop"), null, "gtk-stop");
		this.stopAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Stop");
		w1.Add (this.stopAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Gdk Content Studio");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><toolbar name='mainToolbar'><toolitem name='newAction' action='newAction'/><toolitem name='openAction' action='openAction'/><toolitem name='saveAction' action='saveAction'/><separator/><toolitem name='buildAction' action='buildAction'/><toolitem name='rebuildAction' action='rebuildAction'/><toolitem name='cleanAction' action='cleanAction'/><toolitem name='stopAction' action='stopAction'/></toolbar></ui>");
		this.mainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/mainToolbar")));
		this.mainToolbar.Name = "mainToolbar";
		this.mainToolbar.ShowArrow = false;
		this.mainToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
		this.mainToolbar.IconSize = ((global::Gtk.IconSize)(3));
		this.vbox1.Add (this.mainToolbar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mainToolbar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 327;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 303;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.assetsTree = new global::Gtk.TreeView ();
		this.assetsTree.CanFocus = true;
		this.assetsTree.Name = "assetsTree";
		this.assetsTree.HeadersVisible = false;
		this.assetsTree.RulesHint = true;
		this.GtkScrolledWindow.Add (this.assetsTree);
		this.hpaned1.Add (this.GtkScrolledWindow);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
		w4.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.assetTypeLabel = new global::Gtk.Label ();
		this.assetTypeLabel.Name = "assetTypeLabel";
		this.assetTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Asset:</b>");
		this.assetTypeLabel.UseMarkup = true;
		this.hbox1.Add (this.assetTypeLabel);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.assetTypeLabel]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.assetNameLabel = new global::Gtk.Label ();
		this.assetNameLabel.Name = "assetNameLabel";
		this.assetNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>select an asset</i>");
		this.assetNameLabel.UseMarkup = true;
		this.hbox1.Add (this.assetNameLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.assetNameLabel]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.assetNotebook = new global::Gtk.Notebook ();
		this.assetNotebook.CanFocus = true;
		this.assetNotebook.Name = "assetNotebook";
		this.assetNotebook.CurrentPage = 0;
		this.assetNotebook.TabPos = ((global::Gtk.PositionType)(3));
		// Container child assetNotebook.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 2;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Processor:</b>");
		this.label2.UseMarkup = true;
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(3));
		// Container child hbox2.Gtk.Box+BoxChild
		this.assetProcessorCombo = global::Gtk.ComboBox.NewText ();
		this.assetProcessorCombo.WidthRequest = 250;
		this.assetProcessorCombo.Name = "assetProcessorCombo";
		this.hbox2.Add (this.assetProcessorCombo);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.assetProcessorCombo]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.assetPropertyGrid = new global::Gdk.Framework.UI.GtkSharp.PropertyGrid ();
		this.assetPropertyGrid.Events = ((global::Gdk.EventMask)(256));
		this.assetPropertyGrid.Name = "assetPropertyGrid";
		this.vbox3.Add (this.assetPropertyGrid);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.assetPropertyGrid]));
		w11.Position = 1;
		this.assetNotebook.Add (this.vbox3);
		// Notebook tab
		this.propertiesTabPage = new global::Gtk.Label ();
		this.propertiesTabPage.Name = "propertiesTabPage";
		this.propertiesTabPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Properties");
		this.assetNotebook.SetTabLabel (this.vbox3, this.propertiesTabPage);
		this.propertiesTabPage.ShowAll ();
		// Container child assetNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.assetBuildLogTextView = new global::Gtk.TextView ();
		this.assetBuildLogTextView.CanFocus = true;
		this.assetBuildLogTextView.Name = "assetBuildLogTextView";
		this.GtkScrolledWindow1.Add (this.assetBuildLogTextView);
		this.assetNotebook.Add (this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.assetNotebook [this.GtkScrolledWindow1]));
		w14.Position = 1;
		// Notebook tab
		this.buildLogTabPage = new global::Gtk.Label ();
		this.buildLogTabPage.Name = "buildLogTabPage";
		this.buildLogTabPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Build Log");
		this.assetNotebook.SetTabLabel (this.GtkScrolledWindow1, this.buildLogTabPage);
		this.buildLogTabPage.ShowAll ();
		this.vbox2.Add (this.assetNotebook);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.assetNotebook]));
		w15.Position = 1;
		this.hpaned1.Add (this.vbox2);
		this.vpaned1.Add (this.hpaned1);
		global::Gtk.Paned.PanedChild w17 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hpaned1]));
		w17.Resize = false;
		w17.Shrink = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.bottomNotebook = new global::Gtk.Notebook ();
		this.bottomNotebook.CanFocus = true;
		this.bottomNotebook.Name = "bottomNotebook";
		this.bottomNotebook.CurrentPage = 1;
		this.bottomNotebook.TabPos = ((global::Gtk.PositionType)(3));
		// Container child bottomNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.buildLogTextView = new global::Gtk.TextView ();
		this.buildLogTextView.CanFocus = true;
		this.buildLogTextView.Name = "buildLogTextView";
		this.GtkScrolledWindow3.Add (this.buildLogTextView);
		this.bottomNotebook.Add (this.GtkScrolledWindow3);
		// Notebook tab
		this.bottomNotebookTab1HBox = new global::Gtk.HBox ();
		this.bottomNotebookTab1HBox.Name = "bottomNotebookTab1HBox";
		this.bottomNotebookTab1HBox.Spacing = 6;
		// Container child bottomNotebookTab1HBox.Gtk.Box+BoxChild
		this.bottomNotebookTab1HBoxImage1 = new global::Gtk.Image ();
		this.bottomNotebookTab1HBoxImage1.Name = "bottomNotebookTab1HBoxImage1";
		this.bottomNotebookTab1HBoxImage1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.bottomNotebookTab1HBox.Add (this.bottomNotebookTab1HBoxImage1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab1HBox [this.bottomNotebookTab1HBoxImage1]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child bottomNotebookTab1HBox.Gtk.Box+BoxChild
		this.bottomNotebookTab1HBoxLabel1 = new global::Gtk.Label ();
		this.bottomNotebookTab1HBoxLabel1.Name = "bottomNotebookTab1HBoxLabel1";
		this.bottomNotebookTab1HBoxLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Build Log");
		this.bottomNotebookTab1HBoxLabel1.UseMarkup = true;
		this.bottomNotebookTab1HBox.Add (this.bottomNotebookTab1HBoxLabel1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab1HBox [this.bottomNotebookTab1HBoxLabel1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		this.bottomNotebook.SetTabLabel (this.GtkScrolledWindow3, this.bottomNotebookTab1HBox);
		this.bottomNotebookTab1HBox.ShowAll ();
		// Container child bottomNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.buildErrorsTreeView = new global::Gtk.TreeView ();
		this.buildErrorsTreeView.CanFocus = true;
		this.buildErrorsTreeView.Name = "buildErrorsTreeView";
		this.GtkScrolledWindow2.Add (this.buildErrorsTreeView);
		this.bottomNotebook.Add (this.GtkScrolledWindow2);
		global::Gtk.Notebook.NotebookChild w23 = ((global::Gtk.Notebook.NotebookChild)(this.bottomNotebook [this.GtkScrolledWindow2]));
		w23.Position = 1;
		// Notebook tab
		this.bottomNotebookTab2HBox = new global::Gtk.HBox ();
		this.bottomNotebookTab2HBox.Name = "bottomNotebookTab2HBox";
		this.bottomNotebookTab2HBox.Spacing = 6;
		// Container child bottomNotebookTab2HBox.Gtk.Box+BoxChild
		this.buildErrorsTabImage = new global::Gtk.Image ();
		this.buildErrorsTabImage.Name = "buildErrorsTabImage";
		this.buildErrorsTabImage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
		this.bottomNotebookTab2HBox.Add (this.buildErrorsTabImage);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab2HBox [this.buildErrorsTabImage]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child bottomNotebookTab2HBox.Gtk.Box+BoxChild
		this.buildErrorsTabLabel = new global::Gtk.Label ();
		this.buildErrorsTabLabel.Name = "buildErrorsTabLabel";
		this.buildErrorsTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.buildErrorsTabLabel.UseMarkup = true;
		this.bottomNotebookTab2HBox.Add (this.buildErrorsTabLabel);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab2HBox [this.buildErrorsTabLabel]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child bottomNotebookTab2HBox.Gtk.Box+BoxChild
		this.buildWarningsTabImage = new global::Gtk.Image ();
		this.buildWarningsTabImage.Name = "buildWarningsTabImage";
		this.buildWarningsTabImage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Menu);
		this.bottomNotebookTab2HBox.Add (this.buildWarningsTabImage);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab2HBox [this.buildWarningsTabImage]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		// Container child bottomNotebookTab2HBox.Gtk.Box+BoxChild
		this.buildWarningsTabLabel = new global::Gtk.Label ();
		this.buildWarningsTabLabel.Name = "buildWarningsTabLabel";
		this.buildWarningsTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.buildWarningsTabLabel.UseMarkup = true;
		this.bottomNotebookTab2HBox.Add (this.buildWarningsTabLabel);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab2HBox [this.buildWarningsTabLabel]));
		w27.Position = 3;
		w27.Expand = false;
		w27.Fill = false;
		this.bottomNotebook.SetTabLabel (this.GtkScrolledWindow2, this.bottomNotebookTab2HBox);
		this.bottomNotebookTab2HBox.ShowAll ();
		// Container child bottomNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.buildOutputsTreeView = new global::Gtk.TreeView ();
		this.buildOutputsTreeView.CanFocus = true;
		this.buildOutputsTreeView.Name = "buildOutputsTreeView";
		this.GtkScrolledWindow4.Add (this.buildOutputsTreeView);
		this.bottomNotebook.Add (this.GtkScrolledWindow4);
		global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.bottomNotebook [this.GtkScrolledWindow4]));
		w29.Position = 2;
		// Notebook tab
		this.bottomNotebookTab3HBox = new global::Gtk.HBox ();
		this.bottomNotebookTab3HBox.Name = "bottomNotebookTab3HBox";
		this.bottomNotebookTab3HBox.Spacing = 6;
		// Container child bottomNotebookTab3HBox.Gtk.Box+BoxChild
		this.bottomNotebookTab3HBoxImage1 = new global::Gtk.Image ();
		this.bottomNotebookTab3HBoxImage1.Name = "bottomNotebookTab3HBoxImage1";
		this.bottomNotebookTab3HBoxImage1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-convert", global::Gtk.IconSize.Menu);
		this.bottomNotebookTab3HBox.Add (this.bottomNotebookTab3HBoxImage1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab3HBox [this.bottomNotebookTab3HBoxImage1]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child bottomNotebookTab3HBox.Gtk.Box+BoxChild
		this.bottomNotebookTab3HBoxLabel1 = new global::Gtk.Label ();
		this.bottomNotebookTab3HBoxLabel1.Name = "bottomNotebookTab3HBoxLabel1";
		this.bottomNotebookTab3HBoxLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Build Outputs");
		this.bottomNotebookTab3HBoxLabel1.UseMarkup = true;
		this.bottomNotebookTab3HBox.Add (this.bottomNotebookTab3HBoxLabel1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.bottomNotebookTab3HBox [this.bottomNotebookTab3HBoxLabel1]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		this.bottomNotebook.SetTabLabel (this.GtkScrolledWindow4, this.bottomNotebookTab3HBox);
		this.bottomNotebookTab3HBox.ShowAll ();
		this.vpaned1.Add (this.bottomNotebook);
		global::Gtk.Paned.PanedChild w32 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.bottomNotebook]));
		w32.Resize = false;
		this.vbox1.Add (this.vpaned1);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vpaned1]));
		w33.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 835;
		this.DefaultHeight = 566;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.Window_DeleteEvent);
		this.newAction.Activated += new global::System.EventHandler (this.Toolbar_New_Click);
		this.openAction.Activated += new global::System.EventHandler (this.Toolbar_Open_Click);
		this.saveAction.Activated += new global::System.EventHandler (this.Toolbar_Save_Click);
		this.buildAction.Activated += new global::System.EventHandler (this.Toolbar_Build_Click);
		this.rebuildAction.Activated += new global::System.EventHandler (this.Toolbar_Rebuild_Click);
		this.cleanAction.Activated += new global::System.EventHandler (this.Toolbar_Clean_Click);
		this.stopAction.Activated += new global::System.EventHandler (this.Toolbar_Stop_Click);
		this.assetsTree.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.AssetsTree_ButtonPress);
		this.assetsTree.PopupMenu += new global::Gtk.PopupMenuHandler (this.AssetsTree_PopupMenu);
		this.assetProcessorCombo.Changed += new global::System.EventHandler (this.AssetProperties_ProcessorComboChanged);
		this.assetPropertyGrid.PropertyValueChanged += new global::Gdk.Framework.UI.GtkSharp.PropertyGrid.PropertyHandler (this.AssetProperties_PropertyGridValueChanged);
	}
}
