
// This file has been generated by the GUI designer. Do not modify.
namespace Gdk.Framework.UI.GtkSharp
{
	public partial class PropertyGrid
	{
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.EventBox rootEventbox;
		private global::Gtk.Label label1;
		private global::Gtk.TextView rootPropertyDescription;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Gdk.Framework.UI.GtkSharp.PropertyGrid
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Gdk.Framework.UI.GtkSharp.PropertyGrid";
			// Container child Gdk.Framework.UI.GtkSharp.PropertyGrid.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 203;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.rootEventbox = new global::Gtk.EventBox ();
			this.rootEventbox.Name = "rootEventbox";
			// Container child rootEventbox.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.rootEventbox.Add (this.label1);
			w1.Add (this.rootEventbox);
			this.scrolledwindow1.Add (w1);
			this.vpaned1.Add (this.scrolledwindow1);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.scrolledwindow1]));
			w5.Resize = false;
			w5.Shrink = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.rootPropertyDescription = new global::Gtk.TextView ();
			this.rootPropertyDescription.Buffer.Text = "property.description";
			this.rootPropertyDescription.CanFocus = true;
			this.rootPropertyDescription.Name = "rootPropertyDescription";
			this.rootPropertyDescription.Editable = false;
			this.rootPropertyDescription.WrapMode = ((global::Gtk.WrapMode)(2));
			this.rootPropertyDescription.Indent = 3;
			this.vpaned1.Add (this.rootPropertyDescription);
			global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.rootPropertyDescription]));
			w6.Resize = false;
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
